#!/usr/bin/env bash

build() {
    add_file "/sys/class/tpm/tpm0/device/tpm/tpm0/pcr-sha256/15" "/etc/expectedpcr15"
}

help() {
  cat <<HELPEOF
This hook checks that the TPM's PCR 15 is what's expected, and prompts the
user for confirmation to continue booting if it's not.
HELPEOF
}
