#!/usr/bin/ash

run_hook() {
  local expected actual

  expected=$(cat /etc/expectedpcr15)
  actual=$(cat /sys/class/tpm/tpm0/device/tpm/tpm0/pcr-sha256/15)

  if [ "$expected" != "$actual" ]; then
    echo "WARNING: PCR 15 mismatch"
    echo "Expected: '$expected'"
    echo "Actual:   '$actual'"
    echo
    ""
    echo "This means one of the following:"
    echo "1. Your TPM was reset (through e.g. a BIOS reset), or is malfunctioning."
    echo "2. You changed the partitions that are decrypted or the order they are decrypted in."
    echo "3. Someone else did one of the above. If this has happened, DO NOT enter 'y' below."
    echo ""
    echo -n "Are you sure you want to continue booting ('y' to continue)? "
    read input
    if [ "$input" != "y" ]; then
      echo "Aborting boot."
      return 1
    fi
    echo "Continuing boot in spite of PCR 15 mismatch."
    echo "Run 'mkinitcpio -P' to update this check with the new PCR 15."
  fi

  return 0
}
